#!/bin/sh -e
#<your name> revision date yyyy/mm/dd
#Set initial variables:	

CWD=$(pwd)
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi

# The version which appears in the application's filename
VERSION=${VERSION:-develop}
APP_VERSION=$(echo "$VERSION" | sed -e 's/\//_/g')
#KERNEL=${KERNEL:-$(uname -r)}
#PKGKERNEL=$(echo $KERNEL | tr - _)
REPO_URL=https://github.com/PancakeTAS/lsfg-vk.git
NUMJOBS=${NUMJOBS:-" -j$(nproc) "}

# If the version conflicts with the Slackware package standard
# The dash character ("-") is not allowed in the VERSION string
# You can set the PKG_VERSION to something else than VERSION
#PKG_VERSION=$VERSION # the version which appears in the package name. 

# Automatically determine the architecture we're building on:
if [ -z "$ARCH" ]; then
 case "$( uname -m )" in
   i?86) ARCH=i486 ;;
   arm*) ARCH=arm ;;
   # Unless $ARCH is already set, use uname -m for all other archs:
      *) ARCH=$( uname -m ) ;;
 esac
fi

# First digit is the build number, which specifies how many times it has been built.	
# Second string is the short form of the authors name, typical three initials:w
BUILD=${BUILD:-1}

# The application's name
APP=lsfg

# The installation directory of the package (where its actual directory
# structure will be created) 
PKG=$TMP/package-$APP

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

# Delete the leftover directories if they exist (due to a previous build)
# and (re)create the packaging directory
rm -rf $PKG 
mkdir -p $TMP $PKG
rm -rf $TMP/$APP-$APP_VERSION

# Change to the TMP directory
cd $TMP || exit 1
 
# Extract the application source in TMP
# Note: if your application comes as a tar.bz2, you need tar -jxvf
#tar -zxvf $CWD/$APP-$VERSION.tar.gz || exit 1

git clone  --recurse-submodules --depth 1 --branch=${VERSION} ${REPO_URL} $APP-$APP_VERSION

# Change to the application source directory
cd $APP-$APP_VERSION || exit 1
#get the top commit as #PKG_VERSION
PKG_VERSION=$(git log -n 1 --pretty=format:"%h")
# Change ownership and permissions if necessary
# This may not be needed in some source tarballs, but it never hurts
chown -R root:root .
chmod -R u+w,go+r-w,a-s .

echo Building ...
  cmake -B build-${APP} -G Ninja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_COMPILER=clang \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=On \
    -DCMAKE_INSTALL_PREFIX=/usr

  cmake --build build-${APP} 2>&1 | tee $OUTPUT/make-${PRGNAM}.log
#  cmake --install build-${APP} --prefix $PKG 2>&1 | tee $OUTPUT/install-${PRGNAM}.log
echo Building GUI...
 cd ui
 cargo build --release
 cd $TMP || exit 1
 cd $APP-$APP_VERSION || exit 1
 
#mkdir -p $PKG/etc/rc.d
mkdir -p $PKG/usr/doc/$APP-$APP_VERSION/
mkdir -p $PKG/usr/bin/
mkdir -p $PKG/usr/lib64/
mkdir -p $PKG/usr/share/vulkan/implicit_layer.d/
#mkdir -p $PKG/lib/modules/$KERNEL/extra
mkdir -p $PKG/usr/share/applications/
mkdir -p $PKG/usr/share/icons/hicolor/256x256/apps/

#install -m 0755 $CWD/rc.corefreq $PKG/etc/rc.d/rc.corefreq.new
#install -Dm 0755 build/corefreq-cli build/corefreqd -t $PKG/usr/bin/
#install -m 0644 build/corefreqk.ko $PKG/lib/modules/$KERNEL/extra/
#install -m 0644 $CWD/corefreq.desktop $PKG/usr/share/applications/
install -m 0644 build-${APP}/liblsfg-vk.so $PKG/usr/lib64/
install -m 0644 VkLayer_LS_frame_generation.json $PKG/usr/share/vulkan/implicit_layer.d/
install -m 0755 ui/target/release/lsfg-vk-ui $PKG/usr/bin/
install -m 0644 ui/rsc/gay.pancake.lsfg-vk-ui.desktop $PKG/usr/share/applications/
install -m 0644 ui/rsc/icon.png $PKG/usr/share/icons/hicolor/256x256/apps/gay.pancake.lsfg-vk-ui.png


cp -a \
  LICENSE.md README.md\
  $PKG/usr/doc/$APP-$APP_VERSION/
cat $CWD/$APP.SlackBuild > $PKG/usr/doc/$APP-$APP_VERSION/$APP.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $TMP/$APP-${APP_VERSION}_${PKG_VERSION}-$ARCH-$BUILD.tgz

